### ISSUE TITLE
운동 자세 감지를 위한 운동 종류 선정

### ISSUE THREAD

**Issue by TaeWonM** [TaeWonM/OSS-Basic-Project#13]
- Comment : 운동 자세 감지를 위한 운동 종류 선정
 1. 팔굽혀 펴기
 (+추가) (따로 주가할 내용이 있으면 댓글을 통해서 써주세요)

**Comment by Gorushi** [comment]
2. 스쿼트 (하체 운동)
3. 버피 테스트 (상체 & 하체 운동)

**Comment by TaeWonM** [comment]
#16
1번 항목 구현 완료

**Comment by TaeWonM** [comment]
3. 버피 테스트 측정의 어려움
한번에 3~4가지 동장을 수행해야하는 어려움이 있음

**Comment by TaeWonM** [comment]
여기까지 구현 완료 #33
