### ISSUE TITLE
게임의 종류, 방식 등 전체적인 설계 방향

### ISSUE THREAD

**Issue by Gorushi** [TaeWonM/OSS-Basic-Project#15]
1. 현재까지 확정된 사항
- 사용자가 운동을 하면 점수를 획득
- 운동의 분류 : 상체 / 하체

2. 논의해야할 사항
- 게임의 종류 (링피트 같은 스테이지형 구성 / OO 키우기 와 같은 육성형?)
- 게임의 방식 (게임의 결과가 계속 쌓이는 누적형 / 하루마다 게임이 독립적으로 실행되는 단발형?)

**Comment by TaeWonM** [comment]
게임의 결과가 계속 쌓이는 누적형이 나을것 같습니다

**Comment by TaeWonM** [comment]
게임 구현 완료 #26
