### ISSUE TITLE
Open_pose 처리에 관한 문제

### ISSUE THREAD

**Issue by TaeWonM** [TaeWonM/OSS-Basic-Project#19]
- comment : Open_pose 자체의 모델이 클뿐만 아니라 프로그램이 너무 느려서 아예 삭제를 할지 아니면 프로그램을 개발을 할지 고를 필요성을 느낌
 -  #6

**Comment by Gorushi** [comment]
최종 단계에서도 사용하지 않는다면 그 때 삭제하는 것으로 결정
