### ISSUE TITLE
Open_Pose 실시간 영상 처리 속도가 매우 느림

### ISSUE THREAD

**Issue by Gorushi** [TaeWonM/OSS-Basic-Project#6]
문제 :  https://github.com/TaeWonM/OSS-Basic-Project/pull/4 의 코드를 돌려보면 카메라 영상이 심각할 정도로 끊김 (렉이 심함) 

원인 : 현재 코드는 cpu 를 사용하여 영상을 처리하고 있기 때문에 해당 현상이 발생하는 것으로 추정됨

해결 방법 : 

1. GPU 를 사용하여 영상을 처리하도록 코드를 수정
2. Open_Pose 외에 다른 pose estimation API 사용

한계 :

현재 렉을 최대한 줄이기 위해 영상의 크기를 최대한 작게 설정한 상태임에도 문제가 발생함
테스트 해 본 결과 현재 영상의 크기로는 우리가 원하는 기능 (운동 동작 감지) 을 구현하기에는 어렵다고 판단함
결국 영상의 크기를 2~3배 키워야 하는데 GPU 를 사용한다고 끊기는 현상이 완벽하게 해결되지 않을 것으로 추측됨

**Comment by TaeWonM** [comment]
문제 해결 #11 #12
