### ISSUE TITLE
Open_Pose 를 대체할 수 있는 동작 감지 API 탐색

### ISSUE THREAD

**Issue by Gorushi** [TaeWonM/OSS-Basic-Project#7]
개요 : https://github.com/TaeWonM/OSS-Basic-Project/issues/6#issue-2237590491 의 해결 방안 2번에 대한 자세한 내용

생각해 볼만한 다른 후보 :

1. MediaPipe Pose (https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md)
2. MoveNet (https://www.tensorflow.org/hub/tutorials/action_recognition_with_tf_hub?hl=ko)

참고 자료 :
https://olrlobt.tistory.com/49

**Comment by TaeWonM** [comment]
문제 해결 #11 #12
